import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowUpRight, Download } from 'lucide-react';
import { ResourceShell } from '@/components/resources/resource-shell';
import styles from '@/components/resources/resources.module.css';

export const metadata: Metadata = { title: 'Technical breakdown — RWA Lens', description: 'Architecture, precision, Solana RPC provenance, extension handling and API integration for RWA Lens.', alternates: { canonical: '/technical' } };

const capabilities = [
  ['Mint identity', 'Official codecs distinguish SPL Token and Token-2022. Mint, program, decimals, supply and authorities remain inspectable.'],
  ['Exact accounting', 'Validated token accounts are deduplicated and summed with BigInt. Raw quantities stay decimal strings across the API.'],
  ['Display conversion', 'Scaled UI Amount uses the official conversion helper and observed chain time. Rounding stays separate from raw-unit accounting.'],
  ['Token controls', 'Authority, pause, delegate, default-state, fee and hook evidence is explained alongside known blocks and unknown checks.'],
  ['Source provenance', 'Each read records its method and available context slot. Separate RPC reads retain their own timing and completeness.'],
  ['Portable receipts', 'Guest JSON and CSV exports carry the observation, source details and a SHA-256 content hash. No wallet connection is required.'],
];

export default function TechnicalPage() {
  return (
    <ResourceShell active="technical" eyebrow="INSIDE THE LENS / ENGINEERING" title="Built to make the details add up." description="A read-only inspection pipeline that connects raw Solana account data to usable identity, balance, controls and evidence. Here is how each layer works.">
      <div className={styles.content}>
        <div className={styles.actions}><a className={`${styles.button} ${styles.buttonPrimary}`} href="/presentation/rwa-lens-technical-breakdown.md" download><Download size={16} />Download technical breakdown</a><a className={styles.button} href="https://github.com/operatoruplift/rwa-lens" target="_blank" rel="noreferrer noopener">Explore source <ArrowUpRight size={16} /></a></div>
        <section className={styles.section} aria-labelledby="architecture-title"><p className={styles.label}>01 / ARCHITECTURE</p><h2 id="architecture-title">An observation, end to end.</h2><ol className={styles.flow}><li><strong>Validate</strong><span>Bounded inputs, decoded 32-byte addresses and server-controlled network.</span></li><li><strong>Read</strong><span>Mint, Clock and optional holder accounts through a bounded Solana RPC adapter.</span></li><li><strong>Interpret</strong><span>Official token codecs, exact raw totals, display conversion and control checks.</span></li><li><strong>Explain</strong><span>Typed result, per-call evidence, honest partial states and local receipt export.</span></li></ol><p>The browser calls the application API. Provider credentials and metadata retrieval stay on the server. The product has no transaction-signing, custody or asset-transfer path.</p></section>
        <section className={styles.section}><p className={styles.label}>02 / CAPABILITIES</p><h2>From raw bytes to useful context.</h2><div className={styles.grid}>{capabilities.map(([title, copy], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
        <section className={styles.section}><p className={styles.label}>03 / ACCOUNTING</p><h2>Precision has a boundary.</h2><pre className={styles.code}><code>{'raw total = Σ validated account raw units\nstandard amount = raw total ÷ 10^decimals\nscaled display = official helper(raw total, active multiplier, time)\n\nRaw units → decimal strings / BigInt\nScaled display → labelled floating-point conversion'}</code></pre><p>A display multiplier does not change stored raw units. The active multiplier is selected against the observed Clock sysvar timestamp. A time fallback is explicitly identified; it never becomes an unqualified chain observation.</p><p>USDY is a legacy SPL mint. Its balances use standard decimal conversion. Token-2022 extension logic applies only when those extensions are detected on the inspected mint or account.</p></section>
        <section className={styles.section}><p className={styles.label}>04 / API CONTRACT</p><h2>One request. Traceable results.</h2><pre className={styles.code}><code>{'POST /api/rwa/inspect\nContent-Type: application/json\n\n{\n  "mode": "live",\n  "cluster": "mainnet-beta",\n  "mint": "A1KLoBrKBde8Ty9qtNQUtq3C2ortoC3u7twggz7sEto6"\n}'}</code></pre><p>Add an optional <code>owner</code> address to read public token accounts. The browser cannot select a provider URL. Results distinguish available, partial and unavailable data; identity and balance status are independent.</p><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Field</th><th>Purpose</th></tr></thead><tbody><tr><td><code>identity</code></td><td>Decoded mint, program, decimals and authorities.</td></tr><tr><td><code>balances</code></td><td>Validated accounts, raw total, display amounts and completeness.</td></tr><tr><td><code>extensions / transferReadiness</code></td><td>Detected controls with reasons, evidence and unresolved checks.</td></tr><tr><td><code>provenance</code></td><td>Cluster, provider, method slots, fetched time, chain time and decoder version.</td></tr></tbody></table></div></section>
        <section className={styles.section}><p className={styles.label}>05 / RELIABILITY & SECURITY</p><h2>Fail clearly. Keep the evidence.</h2><div className={styles.grid}><article><h3>Bounded reads</h3><p>Timeouts, aborts, retry budgets, response-size limits and account caps prevent unbounded RPC work. A failed refresh retains the prior observation with its original timestamp.</p></article><article><h3>Untrusted metadata</h3><p>Explicit HTTPS allowlists, private-address rejection, pinned connections and redirect limits constrain metadata fetches. No arbitrary HTML is rendered.</p></article><article><h3>Honest uncertainty</h3><p>Different context slots are not an atomic snapshot. Encrypted amounts, unsupported layouts and unresolved hook behavior stay unknown.</p></article></div><p>Automated coverage includes request schemas, accounting boundaries, token layouts, control classification, provider failures, exports, responsive layouts, keyboard navigation and reduced motion. Hosted checks exercise real mainnet reads separately.</p></section>
        <section className={styles.section}><p className={styles.label}>06 / IMPLEMENTATION SCOPE</p><h2>A clear contract with the user.</h2><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Available</th><th>Boundary</th></tr></thead><tbody><tr><td>Public inspection and local exports</td><td>Read-only, with no wallet connection or asset movement.</td></tr><tr><td>Interest-bearing extension detection</td><td>Interest-bearing conversion is currently unavailable.</td></tr><tr><td>Confidential-transfer detection</td><td>Encrypted balances are not observable through this inspector.</td></tr><tr><td>Transfer control explanations</td><td>Recipient eligibility and execution success are not established.</td></tr><tr><td>Optional private report architecture</td><td>Cloud storage is not enabled in the public release; local exports are available.</td></tr></tbody></table></div></section>
        <section className={styles.section}><p className={styles.label}>PRIMARY REFERENCES</p><ul className={styles.sources}><li><a href="https://docs.ondo.finance/addresses" target="_blank" rel="noreferrer noopener">Ondo mint addresses <ArrowUpRight size={14} /></a></li><li><a href="https://solana.com/docs/tokens/extensions" target="_blank" rel="noreferrer noopener">Solana token extensions <ArrowUpRight size={14} /></a></li><li><a href="https://solana.com/docs/tokens/extensions/scaled-ui-amount" target="_blank" rel="noreferrer noopener">Scaled UI Amount <ArrowUpRight size={14} /></a></li></ul><div className={styles.actions}><Link className={`${styles.button} ${styles.buttonPrimary}`} href="/demo">Try the complete walkthrough <ArrowUpRight size={17} /></Link><Link className={styles.button} href="/pitch">Open the pitch <ArrowUpRight size={17} /></Link></div></section>
      </div>
    </ResourceShell>
  );
}
