import { existsSync, readFileSync, readdirSync, statSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import liveAssets from '@/lib/rwa/live-assets.json';

const root = fileURLToPath(new URL('../..', import.meta.url));

function pageSources(directory: string): string[] {
  return readdirSync(directory, { withFileTypes: true }).flatMap(entry => {
    const full = path.join(directory, entry.name);
    if (entry.isDirectory()) return pageSources(full);
    return entry.isFile() && entry.name.endsWith('.tsx') ? [full] : [];
  });
}

/** Every deliverable the pages advertise is either committed under public/ or is
 * produced by scripts/build-presentation.mjs, whose output list is the contract. */
const generated: string[] = JSON.parse(
  readFileSync(path.join(root, 'scripts/build-presentation.mjs'), 'utf8')
    .match(/const files = (\[[^\]]*\])/)![1]
    .replaceAll("'", '"'),
);

const advertised = [...new Set(
  [...pageSources(path.join(root, 'app')), ...pageSources(path.join(root, 'components'))]
    .flatMap(file => [...readFileSync(file, 'utf8').matchAll(/href="(\/presentation\/[^"]+)"/g)].map(match => match[1])),
)];

describe('advertised resource deliverables', () => {
  it('finds the presentation links the pages offer', () => {
    expect(advertised.length).toBeGreaterThan(0);
  });

  it.each(advertised)('%s is committed or generated by the presentation build', href => {
    const name = href.replace('/presentation/', '');
    expect(existsSync(path.join(root, 'public', href.slice(1))) || generated.includes(name)).toBe(true);
  });

  /** A deployment serves what is present under public/. The pitch kit is written by
   * scripts/build-presentation.mjs, which needs Chromium and pptxgenjs, so a release
   * runs it first (docs/rwa-deployment.md step 2). That exception is pinned: any
   * other advertised deliverable has to be committed to ship at all. */
  const releaseKit = ['rwa-lens-pitch.html', 'rwa-lens-pitch.pptx', 'rwa-lens-pitch.pdf', 'rwa-lens-presenter-notes.md'];

  it('leaves nothing but the documented pitch kit to the release step', () => {
    const uncommitted = [...new Set(advertised.filter(href => !existsSync(path.join(root, 'public', href.slice(1)))).map(href => href.replace('/presentation/', '')))];
    for (const name of uncommitted) expect(releaseKit).toContain(name);
    expect(readFileSync(path.join(root, 'docs/rwa-deployment.md'), 'utf8')).toContain('node scripts/build-presentation.mjs');
  });

  it.each(['rwa-lens-demo-guide.md', 'rwa-lens-technical-breakdown.md'])('%s is a usable document, not a placeholder', name => {
    const file = path.join(root, 'public/presentation', name);
    expect(statSync(file).size).toBeGreaterThan(1000);
    const text = readFileSync(file, 'utf8');
    expect(text).toMatch(/^# RWA Lens/);
    expect(text).not.toMatch(/\bTODO\b|\bTBD\b|coming soon/i);
  });
});

describe('demo page starting paths', () => {
  const intro = readFileSync(path.join(root, 'app/demo/page.tsx'), 'utf8').match(/The inspector below[^<]*/)![0];
  // The inspector renders one preset chip, for the first manifest asset.
  const preset = liveAssets[0];

  it('names the preset the inspector actually renders', () => {
    expect(intro).toContain(preset.symbol);
  });

  it('promises no starting path the inspector does not offer', () => {
    expect(liveAssets).toHaveLength(1);
    expect(intro).not.toMatch(/another listed|other listed|select another|additional asset/i);
    expect(intro).toMatch(/enter a mint of your own/i);
  });
});
